SRCS  = JSONTranscodingOptions.cpp
SRCS += Transcoder.cpp
SRCS += TranscodingOptions.cpp

LIB = Transcoder.a

include /home/mark/GSoC-2015/xbmc/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
